# Generated by Django 3.1.3 on 2020-11-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='priceL',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='priceM',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
